### ISSUE TITLE
transfer ownership of repo?

### ISSUE THREAD

**Issue by achubaty** [ilaneshaw/postHocBinning#2]
I'm assuming @ilaneshaw doesn't want to provide ongoing updates and maintain this module going forward, so we should consider giving it a new home.

Either `PredictiveEcology` or `FOR-CAST`.

**Comment by ilaneshaw** [comment]
That seems sensible- how do I facilitate this?

**Comment by achubaty** [comment]
https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository#transferring-a-repository-owned-by-your-user-account

**Comment by achubaty** [comment]
bumping this

**Comment by ilaneshaw** [comment]
Hi Alex, sorry- I transferred it to your account (achubaty) on Saturday rather than PredictiveEcology or FOR-CAST. I just tried to send it to those two, but for both of them I got the message that I don't have permission to post stuff to those accounts, so I have sent it again to your account.
